// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGV_BxqvvfVqAVo9vthZcGtfrSar58c5s',
    appId: '1:926389865703:web:141b87a63a0cae4f51e642',
    messagingSenderId: '926389865703',
    projectId: 'flutter-chat-f1496',
    authDomain: 'flutter-chat-f1496.firebaseapp.com',
    storageBucket: 'flutter-chat-f1496.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDklzXqK-nUzZlismdNaYb8a1e35KymlTw',
    appId: '1:926389865703:android:e684504feb2cc0c051e642',
    messagingSenderId: '926389865703',
    projectId: 'flutter-chat-f1496',
    storageBucket: 'flutter-chat-f1496.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeNT5pIa3GVVwJPhtT2jpTB4XEAj0X3Rk',
    appId: '1:926389865703:ios:9fd5592798015fbe51e642',
    messagingSenderId: '926389865703',
    projectId: 'flutter-chat-f1496',
    storageBucket: 'flutter-chat-f1496.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeNT5pIa3GVVwJPhtT2jpTB4XEAj0X3Rk',
    appId: '1:926389865703:ios:9fd5592798015fbe51e642',
    messagingSenderId: '926389865703',
    projectId: 'flutter-chat-f1496',
    storageBucket: 'flutter-chat-f1496.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGV_BxqvvfVqAVo9vthZcGtfrSar58c5s',
    appId: '1:926389865703:web:65e11d5a96ac717051e642',
    messagingSenderId: '926389865703',
    projectId: 'flutter-chat-f1496',
    authDomain: 'flutter-chat-f1496.firebaseapp.com',
    storageBucket: 'flutter-chat-f1496.firebasestorage.app',
  );
}
